Adding most functionalities to main
MartijnvCitteren/music_bingo pull request #8
Opened 2023-09-29 14:55 UTC by MartijnvCitteren

What is done:

* read xlxs re-wrote, orignial output was a data-frame that wasn't (easy) to index. Wrote a fruntion that put all artists and sons in a list.

* format string Created a format string method. Artist and title on top each other and are allwats alligned centerd.

* Made some adjustments to the Xlxs file: added headers.

* from template to pdf 1- adjust picture to have it stright while printing text and rotate it 90 degrees afterwards. 2- copied the image part to 'print_bingo_card_image' to experiment how we can best print all values on a bingo card.

* main added all the functionalities (that are done) in main

How to test:
pull the branch, run the main - code using the xlxs and template in file.

2023-09-30 11:56 UTC, Julien-Groenenboom commented on RandomBingoAlgorithm.py
**Variable Naming**: You have defined n_participants and card_size as global variables, but within the random_bingo_vars function, you redefine card_size. It's better to use the card_size parameter you passed to the function to avoid confusion.

**Commented-out Code**: The commented-out code within the function doesn't serve any purpose and can be removed. If you had a specific reason for it, please provide more context.

**Unused Global Variable**: You defined n_participants as a global variable, but you are not using it within the function. If it's meant to represent the number of bingo cards you want to generate, consider using it as an argument for the function.

**Function Return**: The function doesn't return anything. If you want to use the generated bingo cards outside the function, you should return them.

**Scraps**: In the end, we might only need "random.sample(song_and_artist, card_size)" from this code snippet as we'll not print() the artists+title to screen. Furthermore, if we want to pass 9 title+artists, we can do that it one variable (instead of creating a lot of additional variables like 'spot_2'). In case we need 4x4 bingo or 5x5, that would otherwise mean you need to create more 'spot_*'-variables. I suggest moving this file to 'scraps'.

2023-09-30 12:10 UTC, Julien-Groenenboom commented on format_string.py
"elif length_title <= length_artist:" can be replaced by "else:".

This function expects input in the format "<title>--<artist>".  That would require combining the title and artist before providing it to this function. Might be better to use title and artist as two separate input arguments.

Using this function, the printed artist and title will be centered (when compared to each other), but that doesn't mean that it is printed 'centered' on the image/bingocard. So I think this is something that needs to be handled when placing the text on the image.

2023-09-30 12:13 UTC, Julien-Groenenboom commented on main.py
review by ChatGPT (used in one of the above reviews as well .. )

Overall, your code appears to be in good shape, but there are some improvements and recommendations to consider:

Imports Ordering: It's common practice to organize import statements. Typically, standard library imports come first, followed by third-party library imports, and then your own module imports. Make sure to arrange your imports in a clear and consistent manner.

Code Separation: You might want to separate your code into functions or classes to make it more modular and maintainable. This will help you reuse parts of your code if needed and make the logic easier to understand.

Variable Naming: Variable names like xlsx_path, jpg_path, and pdf_path are good, but variable names like j and song could be more descriptive. Using descriptive variable names improves code readability.

Comments and Documentation: Add comments or docstrings to explain the purpose of your functions and any non-obvious logic. This will make it easier for others (and yourself) to understand your code in the future.

Error Handling: Consider adding error handling for potential issues, such as file not found or user input errors. This will make your program more robust.

Logic for Creating Bingo Cards: You mention having a while loop for creating bingo cards, but your code currently generates only one bingo card. You can extend your code to create multiple bingo cards within the loop.

Code Organization: Your code currently combines different tasks, such as file input, bingo card generation, and text formatting. Consider organizing these tasks into separate functions or classes for better code organization and maintainability.

Here's a refactored version of your code with some of these recommendations applied

```
from tkinter import filedialog, simpledialog
import tkinter as tk
import random
from scraps import read_xlsx
import format_string

def get_file_path(title, filetypes):
    root = tk.Tk()
    root.withdraw()
    root.call('wm', 'attributes', '.', '-topmost', True)
    file_path = filedialog.askopenfilename(title=title, filetypes=filetypes)
    return file_path

def get_integer_input(prompt, title):
    root = tk.Tk()
    root.withdraw()
    root.call('wm', 'attributes', '.', '-topmost', True)
    value = simpledialog.askinteger(title, prompt)
    return value

def create_bingo_card(songs_and_artists, card_size):
    return random.sample(songs_and_artists, card_size)

def main():
    xlsx_path = get_file_path("Open Excel-bestand met titel en artiesten...", [("Excel Files", "*.xlsx")])
    print("Locatie Excelbestand:", xlsx_path)

    jpg_path = get_file_path("Open JPG-bestand met de bingokaart...", [("JPG Files", "*.jpg")])
    print("Locatie JPG-bestand:", jpg_path)

    no_cards = get_integer_input("Aantal bingokaarten:", "Aantal bingokaarten")
    print("Aantal bingokaarten:", no_cards)

    pdf_path = filedialog.asksaveasfilename(title="Sla het PDF-bestand op als...", filetypes=[("PDF Files", "*.pdf")], defaultextension=".pdf")

    songs_and_artists = read_xlsx.xlsx_to_list(xlsx_path)

    for _ in range(no_cards):
        card_size = 9  # Change this to your desired card size
        bingocard = create_bingo_card(songs_and_artists, card_size)

        for song in bingocard:
            artist, song = format_string.format_output(song)
            print(artist)
            print(song)

if __name__ == "__main__":
    main()
```

2023-09-30 12:17 UTC, Julien-Groenenboom commented on scraps/from_template_to_pdf.py
Instead of using 'image_final' , I suggest using 'image_rotated'. In case we'll add another operation to the image, 'image_final' won't be a proper name anymore.

2023-09-30 12:21 UTC, Julien-Groenenboom commented on scraps/read_xlsx.py
It is possible to apply indexing to a pandas dataframe and even more options than just selecting the location within an array: 
https://pandas.pydata.org/docs/user_guide/indexing.html

However, for this application, it does not really matter which kind of type is used.

2023-09-30 12:27 UTC, Julien-Groenenboom requested changes
And next to some comments on files:
Let's discuss a structure of the music_bingo folder. You are now using some first code snippets/scraps in the 'final' code by using 'from scraps import..' whereas the functions that eventually will be used should be stored in a different location.

2023-10-03 14:41 UTC, MartijnvCitteren commented on scraps/read_xlsx.py
### **Read Xlsx**

- Splitting and concatenating:  Fair point; this could be done cleaner. With a list, I needed to figure out a way to shuffle artists and songs together and format them centered.  _Do you know a way to do this?_

- Seperator: We could fix this by creating a variable to store a separation variable.  But because this var will be used in different Python files and different functions, I think we add too much complexity for the POC. Let's refactor this later. 

### **from template to pdf**

> Instead of using 'image_final' , I suggest using 'image_rotated'. In case we'll add another operation to the image, 'image_final' won't be a proper name anymore. 

- Agree! done

### **format string**
> "elif length_title <= length_artist:" can be replaced by "else:".

- Agree. We could change this back later and add an 'else' or try statement for error handling If there is, for example no artist in the Excel. 

>This function expects input in the format "<title>--". That would require combining the title and artist before providing it to this function. It might be better to use title and artist as two separate input arguments.

- Thats hard. We format the string as a final step. We need to have a way to keep the title and artist stored in the same variable before randomly shuffeling them. After the random shuffle, we can seperate them again.

>Using this function, the printed artist and title will be centered (when compared to each other), but that doesn't mean that it is printed 'centered' on the image/bingocard. So I think this is something that needs to be handled when placing the text on the image.

- Aah, yes, you're right. The print-on-picture function starts typing it the given coordinates... It makes printing multiple variables on one picture even a bit harder. We can reuse this logic tough. 


###**Random Bingo Algorithm**

- I think everything in this file could be better added to main. Because after each loop a new bingo card should be printed. Combining the random_function and print_function is unlogical I think. It's more transparent for others and our future selves if this logic happens in the main. Agree?

When doing this, we can directly add your other suggested improvements. 


### **main**
Great suggestions ;) main is adjusted.




**will commit and push all adjustments by the end of the day.**

2023-10-03 14:49 UTC, MartijnvCitteren commented
> And next to some comments on files: Let's discuss the structure of the music_bingo folder. You are now using some first code snippets/scraps in the 'final' code by using 'from scraps import..' whereas the functions that eventually will be used should be stored in a different location.

Yes, fair point! I'm not sure, but I thought the advantage of using Git is that you can create multiple branches that you merge into your main branch if everything works.  With the scraps folder, it looks like we're doing this manually.  [`page with info`](https://codeinstitute.net/nl/blog/git-branches/#:~:text=Git%20Branches%20allow%20us%20to%20create%20separate%20contexts%20where%20we,merge%20or%20integrate%20the%20changes.)

2023-10-04 08:57 UTC, Julien-Groenenboom requested changes

2023-10-04 08:57 UTC, Julien-Groenenboom commented on RandomBingoAlgorithm.py
- [ ] add card_size as (optional, with default value) variable: def random_bingo_vars(songs_and_artists, no_cards, **card_size=9**):
- [ ] Added a check if the square root of card_size is an integer. If not, raise an error. (Not just print "ERROR", but stop the program)
- [ ] Instead of a while-loop, I suggest a for-loop.
- [ ] Append the bingocards and return them. Or print the results. At the moment, there is no output of this script/function.

2023-10-04 08:57 UTC, Julien-Groenenboom commented on split_string.py
The comment/description is not correct. 
This function is not used (anymore) ?

2023-10-04 18:47 UTC, merged

2023-10-04 18:48 UTC, Julien-Groenenboom commented
Nice work :) I merged this branch to main. 
I think you are done using this branch, right? If so, please click 'Delete branch'.